[package]
name = "ctodomvc"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
spair = { path = "../../spairc", package = "spairc" }
serde = { version = "1.0", features = ["derive"] }
gloo-storage = "0.3"
wasm-logger = "0.2"
log = "0.4"
